### ISSUE TITLE
static willTransitionTo is lost

### ISSUE THREAD

**Issue by jonathanewerner** [gaearon/babel-plugin-react-transform#25] opened 2015-09-22 14:14 UTC
i'm not sure if this is the fault of babel-plugin-react-transform. After integrating react-transform-boilerplate into our setup, `static willTransitionTo` is gone on components. i guess it gets lost in the process of wrapping the component with a HOC?

**Comment by gaearon** [comment] 2015-09-22 14:37
Please provide a reproducible example. Babel plugin doesn't add any HOCs.

**Comment by jonathanewerner** [comment] 2015-09-22 19:27
Ok, i investigated some more. 
The problem is the following:
We use fluxible, which provides the [`provideContext` helper](https://github.com/yahoo/fluxible-addons-react/blob/master/provideContext.js), which wraps your root component by returning a HOC that injects context into its its wrapped component. it copies over statics by using [hoist-non-react-statics](https://www.npmjs.com/package/hoist-non-react-statics), which in turn uses `    var keys = Object.getOwnPropertyNames(sourceComponent)` to get the relevant statics. When console.logging those `keys` *without* using this plugin, this returns an array that contains "willTransitionTo". When using *with* this plugin, the array *doesn't* contain "willTransitionTo" (just `["length", "name", "arguments", "caller", "prototype", "displayName", "__reactPatchProxy", "contextTypes"]`). 

I am not sure if this is expected behaviour, as I do not entirely understand the [limitations section of your react-proxy README](https://github.com/gaearon/react-proxy#known-limitations):
> Does not replace ES7 instance properties
Does not replace bound static methods
Replacing a method using autobind-decorator causes its identity to change

(I don't find google results for "ES7 instance properties" and "bound static methods" -- excuse my ignorance :))

**Comment by gaearon** [comment] 2015-09-22 19:39
Closing as duplicate of https://github.com/gaearon/react-proxy/issues/23.

**Closed by gaearon** 2015-09-22 19:39 UTC

**Comment by jonathanewerner** [comment] 2015-09-22 20:52
Ok thanks for confirming, will watch there!

**Comment by gaearon** [comment] 2015-09-23 00:32
Just to clarify—this is not related to limitations in README, those are only talking about what's hot reloaded. The problem is a side effect of the way static properties are currently being proxied.

**Comment by gaearon** [comment] 2015-09-25 20:17
Thank you for reporting this.
It should be fixed in `react-transform-hmr@1.0.1` via `react-proxy@1.1.1` (https://github.com/gaearon/react-proxy/pull/29).
Please verify.

**Comment by jonathanewerner** [comment] 2015-09-26 14:54
Awesome. Works! Thank you so much. :) deploying react-transform to all of
our projects now. Yey :)

Dan Abramov <notifications@github.com> schrieb am Fr., 25. Sep. 2015 22:17:
