### ISSUE TITLE
Ember objects detected as react components

### ISSUE THREAD

**Issue by mattijauhiainen** [gaearon/babel-plugin-react-transform#81] opened 2016-02-01 04:26 UTC
react-transform seems to mistake ember objects with `render` method as react components. A testcase with few examples of typical syntax. Changing the method name to `_render` 'fixes' the test. https://github.com/mattijauhiainen/babel-plugin-react-transform/commit/dbfbf5d2bf14177595bd0eeb0cec020c7aabb4e1

**Comment by nfcampos** [comment] 2016-02-17 23:00
I'm guessing this does not do what we want?
https://github.com/babel/babel/blob/master/packages/babel-types/src/react.js#L5

**Comment by gaearon** [comment] 2016-02-18 00:12
@nfcampos 

I don’t think we use that function.
No, we can’t inspect the prototype because this is compile time, not run time.
I think the bug, if there is one, is somewhere here: https://github.com/gaearon/babel-plugin-react-transform/blob/63cafc90625c99783d4ba793d58bb59523624364/src/index.js#L5-L9

**Comment by gaearon** [comment] 2016-02-18 00:14
Or, rather, the problem is most likely that these two lines should end with `||` rather than `&&`:

https://github.com/gaearon/babel-plugin-react-transform/blob/63cafc90625c99783d4ba793d58bb59523624364/src/index.js#L77

https://github.com/gaearon/babel-plugin-react-transform/blob/63cafc90625c99783d4ba793d58bb59523624364/src/index.js#L122

Please feel free to submit a fix, add tests for it, and I’ll be happy to merge.

**Comment by gaearon** [comment] 2016-02-18 00:16
Closing as duplicate of #84. (This one is earlier but the other one describes the problem more accurately).

**Closed by gaearon** 2016-02-18 00:16 UTC

**Comment by gaearon** [comment] 2016-03-04 18:43
Should be fixed in 2.0.1.
